//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUNIVERSIDAD.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universidad
    {
        public int iduniversidad { get; set; }
        public string nombreuniversidad { get; set; }
        public string nombrecomercial { get; set; }
        public string tipouniversidad { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string localizacion { get; set; }
        public string estado { get; set; }
    }
}
